FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml README.md ./
COPY symposa ./symposa
COPY plugins/symposa ./plugins/symposa
RUN pip install --no-cache-dir -e ".[symposa]"
ENV SYMPOSA_API_PORT=8090
EXPOSE 8090
CMD ["symposa-api"]
